# Generated by Django 4.2.3 on 2023-07-29 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.CharField(max_length=3)),
                ('patient_email', models.EmailField(max_length=50)),
                ('patient_gender', models.CharField(max_length=7)),
                ('patient_phone', models.CharField(max_length=20)),
                ('appoinment_date', models.DateField(null=True, verbose_name='Appoinment Date')),
                ('serial_number', models.IntegerField(verbose_name='Serial Number')),
                ('user_id', models.IntegerField(verbose_name='User_id')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_name', to=settings.AUTH_USER_MODEL, verbose_name='Doctor Name')),
            ],
            options={
                'db_table': 'appoinment',
            },
        ),
    ]
